### PR TITLE
fix(modal): update taskbar icon and text on modal change

### LINKED ISSUE #231: When a Window title changes, it doesn't update in taskbar
Possibly it is due to incorrect use of the library, but on the 95 Recipes showcase, I found the following bug.

If you have a Window open and its title changes, the change won't be reflected in the Taskbar.

Steps to reproduce:
1. open https://95recipes.ggdaltoso.dev/#/torta-de-frango
2. a recipe will be already open (Torta de Frango) and the correct window title is shown in the Taskbar
3. click on another recipe
4. the title in the Taskbar is still _Torta de Frango_

### PR DESCRIPTION
**Pull request by kirkobyte**
Makes the ModalProvider state update as required for modal titles and icons to be updated in the
taskbar if they're changed in the modals.

Also fixes the bug that would remove all instances of a modal with the same title when one is removed.

IDs were added to the modals, and used to reference removal and/or update of modals. For backwards compatibility, if anyone's using the modal provider directly, I've kept the current method for removing modals as-is

fixes: #231

### CODE REVIEW

**Comment by kirkobyte** [comment]
Do we have any existing library for creating randomised IDs? I added `nanoid` since it does the job nicely and is a super small library

File: packages/core/components/Modal/ModalProvider.tsx [hunk 1]
```diff
@@ -1,26 +1,91 @@
...
-  const addWindows = (window: Windows) =>
-    setWindows(state => [...state, window]);
-  const removeWindows = (title: string) =>
-    setWindows(state => state.filter(w => w.title !== title));
+  const addWindows = (window: Windows) => {
+    const id = nanoid();
+    dispatch({ type: 'ADD_WINDOW', id, window });
+    return id;
+  };
+  // TODO: Remove this method in the next major release - updating by IDs is more sensible
```
Comment (ggdaltoso) [inline packages/core/components/Modal/ModalProvider.tsx:70]: Is this related to #194?

We could also remove it in the next minor release since your PR makes `removeWindows` obsolete.

Meanwhile, it is not a public API. ModalContext handles which window should be removed/updated so I don't think we should publish a major version about this. What do you think?

File: packages/core/components/Modal/ModalProvider.tsx [hunk 2]
```diff
@@ -1,26 +1,91 @@
...
+      newWindows[action.id] = action.window;
+      return newWindows;
+    }
+    case 'REMOVE_BY_TITLE': {
+      Object.entries(newWindows).forEach(([id, window]) => {
+        if (window.title === action.title) {
+          delete newWindows[id];
+        }
+      });
+      return newWindows;
```
Comment (ggdaltoso) [inline packages/core/components/Modal/ModalProvider.tsx:54]: wouldn't `.filter` be better?

*_it is not a suggestion, btw_

**Review by ggdaltoso — CHANGES_REQUESTED** [review]
Very nice job!

File: packages/core/components/Modal/ModalProvider.tsx (hunk 2 above)
Comment (kirkobyte) [reply packages/core/components/Modal/ModalProvider.tsx:54]: `.filter` doesn't really work here since `state`/`newWindows` is an object map rather than an array. It could maybe be done by filtering on the object keys, then reassigning the object keys. But that's not really a clear pattern to read 😕

File: packages/core/components/Modal/ModalProvider.tsx (hunk 1 above)
Comment (kirkobyte) [reply packages/core/components/Modal/ModalProvider.tsx:70]: While it wasn't intended to be part of a public API, it is accessible, so removing the method could break things for someone consuming using the provider directly for some purpose we haven't thought of. E.g. if a user wanted to manually manage what is shown in `Taskbar`

Comment (kirkobyte) [reply packages/core/components/Modal/ModalProvider.tsx:70]: I think a bit of additional work would be required to solve #194, since I tried to keep the rest of the API for this the same.

If we changed the API for the value of `ModalContext` to be the full object, with IDs, and used those IDs to manage the focus state, then I think that would solve #194

**Comment by ggdaltoso** [comment]
> Do we have any existing library for creating randomised IDs? I added `nanoid` since it does the job nicely and is a super small library

NanoID seems to be awesome for this! So tiny library! We can keep it!

File: packages/core/components/Modal/ModalProvider.tsx (hunk 1 above)
Comment (kirkobyte) [reply packages/core/components/Modal/ModalProvider.tsx:71]: Ah, I just re-read #194, yeah, this change would fix that problem. When I initially read it, I thought it was about focus states, which this doesn't deal with. The latest commit I've pushed deals with that issue, but if we want to keep the changes to the provider less breaking, I can pop that commit

**Review by ggdaltoso — APPROVED** [review]
Everything looks great! You have my approval

But, before we merge it into master, if we do this by the way the commits messages were written, we will have this new version:

``` 
@react95/core: 4.1.3 => 4.1.4 
```

Are we good?

**Comment by kirkobyte** [comment]
The `ModalProvider` state has a breaking change, so if we were to be purely semantic about it, it would be a breaking change. But I'm happy to go with your judgement on whether you're wanting to treat that as an internal API detail :)

**Comment by ggdaltoso** [comment]
> The `ModalProvider` state has a breaking change, so if we were to be purely semantic about it, it would be a breaking change. But I'm happy to go with your judgement on whether you're wanting to treat that as an internal API detail :)

I agree about the breaking change. We just need to edit any commit message and add a `BREAKING CHANGE: ${message}` to the body so we can publish v5.0.0 using our CI

**Comment by kirkobyte** [comment]
Great! I've added a breaking change commit to remove that old "removeWindows" method for removing window by title :)

**Comment by ggdaltoso** [comment]
Now we're good!
